import {S,log} from './state.js';import {rad} from './utils.js';
export function generateGrid(rows,cols,spacingD){const {lat,lon,rotorD,hubHeight}=S.project;const spacing=spacingD*rotorD;const mx=111320*Math.cos(rad(lat)),my=111320;const out=[];let id=1;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const x=(c-(cols-1)/2)*spacing,y=(r-(rows-1)/2)*spacing;out.push({id:id++,name:`T${id-1}`,lat:lat+y/my,lon:lon+x/mx,hh:hubHeight})}S.turbines=out;log(`Generated ${out.length} turbines (${spacingD}D spacing)`);return out}
function addPoint(pts,lat,lon,name=''){if(Number.isFinite(lat)&&Number.isFinite(lon)&&Math.abs(lat)<=90&&Math.abs(lon)<=180)pts.push({lat,lon,name})}
function parseKml(text){const pts=[];const pmRe=/<Placemark[\s\S]*?<\/Placemark>/gi;let pm;let any=false;while((pm=pmRe.exec(text))){any=true;const block=pm[0];const nm=(block.match(/<name[^>]*>([\s\S]*?)<\/name>/i)?.[1]||'').replace(/<[^>]+>/g,'').trim();const coordRe=/<Point[\s\S]*?<coordinates[^>]*>([\s\S]*?)<\/coordinates>[\s\S]*?<\/Point>/gi;let m;while((m=coordRe.exec(block))){for(const tok of m[1].trim().split(/\s+/)){const [lon,lat]=tok.split(',').map(Number);addPoint(pts,lat,lon,nm)}}}
 if(!any){const re=/<coordinates[^>]*>([\s\S]*?)<\/coordinates>/gi;let m;while((m=re.exec(text))){for(const tok of m[1].trim().split(/\s+/)){const [lon,lat]=tok.split(',').map(Number);addPoint(pts,lat,lon)}}}
 return pts}
function parseCsv(text){const pts=[];const lines=text.split(/\r?\n/).filter(l=>l.trim());if(!lines.length)return pts;const sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':(lines[0].includes('\t')?'\t':',');const header=lines[0].split(sep).map(h=>h.trim().toLowerCase());const hasHead=header.some(h=>['lat','latitude','lon','lng','longitude','x','y'].includes(h));const latI=header.findIndex(h=>h==='lat'||h==='latitude'||h==='y');const lonI=header.findIndex(h=>h==='lon'||h==='lng'||h==='longitude'||h==='x');const nameI=header.findIndex(h=>h==='name'||h==='turbine'||h==='wtg'||h==='id');const start=hasHead?1:0;for(let i=start;i<lines.length;i++){const c=lines[i].split(sep).map(x=>x.trim().replace(/^"|"$/g,''));let lat,lon,name=`T${i+1}`;if(latI>=0&&lonI>=0){lat=Number(c[latI]);lon=Number(c[lonI]);if(nameI>=0)name=c[nameI]||name}else{const nums=c.map(Number);if(Number.isFinite(nums[1])&&Number.isFinite(nums[2])){name=c[0]||name;lat=nums[1];lon=nums[2]}else if(Number.isFinite(nums[0])&&Number.isFinite(nums[1])){lat=nums[0];lon=nums[1]}}
 addPoint(pts,lat,lon,name)}return pts}
export function parseLayout(text){let pts=[];if(text.includes('<kml')||text.includes('<coordinates')||text.includes('<Placemark'))pts=parseKml(text);else pts=parseCsv(text);const seen=new Set();pts=pts.filter(p=>{const k=p.lat.toFixed(7)+','+p.lon.toFixed(7);if(seen.has(k))return false;seen.add(k);return true}).map((p,i)=>({id:i+1,name:p.name||`T${i+1}`,lat:p.lat,lon:p.lon,hh:S.project.hubHeight}));S.turbines=pts;if(!pts.length)log('Loaded 0 turbine points — use CSV name,lat,lon or KML/KMZ Point placemarks','w');else log(`Loaded ${pts.length} unique turbine points`);return pts}
export async function parseLayoutFile(file){const name=(file.name||'').toLowerCase();if(name.endsWith('.kmz')){if(!globalThis.JSZip)throw Error('KMZ support requires JSZip CDN; try unzipping KMZ and upload doc.kml');const zip=await globalThis.JSZip.loadAsync(await file.arrayBuffer());let kmlName=Object.keys(zip.files).find(n=>n.toLowerCase().endsWith('.kml'));if(!kmlName)throw Error('KMZ has no KML file');return parseLayout(await zip.files[kmlName].async('text'))}return parseLayout(await file.text())}
