const $=id=>document.getElementById(id);const rad=d=>d*Math.PI/180;const gamma=z=>{if(z<.5)return Math.PI/(Math.sin(Math.PI*z)*gamma(1-z));z-=1;const p=[.9999999999998099,676.5203681218851,-1259.1392167224028,771.3234287776531,-176.6150291621406,12.507343278686905,-.13857109526572012,9.984369578019572e-6,1.5056327351493116e-7];let x=p[0];for(let i=1;i<p.length;i++)x+=p[i]/(z+i);const t=z+7.5;return Math.sqrt(2*Math.PI)*Math.pow(t,z+.5)*Math.exp(-t)*x};
const S={turbines:[],boundary:[],constraints:[],terrain:null,roughness:[],climate:null,era5:null,mastTS:null,pc:null,results:null,ts:null,layers:{},mode:null,tempPoly:[]};
function log(m,t='I'){const el=$('log');el.textContent+=`\n[${new Date().toLocaleTimeString()}] ${t} ${m}`;el.scrollTop=1e9;console.log(m)}
function P(){return{project:$('project').value,lat:+$('refLat').value,lon:+$('refLon').value,refH:+$('refH').value,hubH:+$('hubH').value,D:+$('rotD').value,rated:+$('rated').value,z0:+$('z0').value,loss:+$('loss').value/100,wakeK:+$('wakeK').value,wake:$('wakeModel').value,rhoRef:+$('rhoRef').value,temp:+$('temp').value,elev:+$('elev').value}}
let map;function initMap(){map=L.map('map',{preferCanvas:true}).setView([+$('refLat').value,+$('refLon').value],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OSM'}).addTo(map);for(const k of ['wtg','boundary','constraints','terrain','rough','wind'])S.layers[k]=L.layerGroup().addTo(map);map.on('click',e=>{if(S.mode==='wtg')addTurbine(e.latlng.lat,e.latlng.lng);else if(S.mode==='boundary'||S.mode==='constraint'){S.tempPoly.push([e.latlng.lat,e.latlng.lng]);drawTemp()}})}
function drawTemp(){S.layers.boundary.clearLayers();if(S.boundary.length)L.polygon(S.boundary,{color:'#3fb950',weight:2,fillOpacity:.05}).addTo(S.layers.boundary);if(S.tempPoly.length)L.polyline(S.tempPoly,{color:'#d29922',dashArray:'4 4'}).addTo(S.layers.boundary);drawConstraints();drawTurbines()}
function drawConstraints(){S.layers.constraints.clearLayers();for(const c of S.constraints)L.polygon(c,{color:'#f85149',weight:2,fillOpacity:.18}).addTo(S.layers.constraints)}
function closePoly(){if(S.tempPoly.length<3)return; if(S.mode==='boundary')S.boundary=[...S.tempPoly]; else if(S.mode==='constraint')S.constraints.push([...S.tempPoly]);S.tempPoly=[];drawAll();log('Polygon closed')}
function clearDraw(){S.boundary=[];S.constraints=[];S.tempPoly=[];drawAll();log('Boundary/constraints cleared')}
function addTurbine(lat,lon,name){const t={id:S.turbines.length+1,name:name||`T${S.turbines.length+1}`,lat,lon,hh:P().hubH};S.turbines.push(t);drawTurbines();log(`Added ${t.name}`)}
function drawTurbines(){S.layers.wtg.clearLayers();for(const t of S.turbines){const m=L.marker([t.lat,t.lon],{draggable:true}).bindPopup(`<b>${t.name}</b><br>${t.lat.toFixed(5)}, ${t.lon.toFixed(5)}`).addTo(S.layers.wtg);m.on('dragend',e=>{const ll=e.target.getLatLng();t.lat=ll.lat;t.lon=ll.lng})}}
function drawAll(){drawTemp();drawTurbines();drawTerrain();drawRough();drawWindMap();}
function fitAll(){const pts=[...S.turbines.map(t=>[t.lat,t.lon]),...S.boundary];if(pts.length)map.fitBounds(L.latLngBounds(pts).pad(.15),{maxZoom:13});}
function pointInPoly(pt,poly){let c=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const yi=poly[i][0],yj=poly[j][0],xi=poly[i][1],xj=poly[j][1];if(((yi>pt[0])!==(yj>pt[0]))&&(pt[1]<(xj-xi)*(pt[0]-yi)/((yj-yi)||1e-12)+xi))c=!c}return c}
async function importFile(file){const n=file.name.toLowerCase();let txt;if(n.endsWith('.kmz')){const z=await JSZip.loadAsync(await file.arrayBuffer());const k=Object.keys(z.files).find(x=>x.toLowerCase().endsWith('.kml'));txt=await z.files[k].async('text')}else txt=await file.text();if(n.endsWith('.json')||n.endsWith('.geojson'))return importGeoJSON(JSON.parse(txt));if(txt.includes('<coordinates'))return importKML(txt);return importCSV(txt)}
function importCSV(txt){const lines=txt.split(/\r?\n/).filter(Boolean);const sep=lines[0].includes(';')?';':(lines[0].includes('\t')?'\t':',');const h=lines[0].split(sep).map(x=>x.toLowerCase().trim());const has=h.some(x=>x==='lat'||x==='latitude');let start=has?1:0,latI=h.findIndex(x=>x==='lat'||x==='latitude'||x==='y'),lonI=h.findIndex(x=>x==='lon'||x==='lng'||x==='longitude'||x==='x'),nameI=h.findIndex(x=>x==='name'||x==='wtg'||x==='id');S.turbines=[];for(let i=start;i<lines.length;i++){const c=lines[i].split(sep).map(x=>x.trim());let lat,lon,name;if(has){lat=+c[latI];lon=+c[lonI];name=c[nameI]||''}else{lat=+c[1];lon=+c[2];name=c[0]||'';if(!isFinite(lat)||!isFinite(lon)){lat=+c[0];lon=+c[1]}}if(isFinite(lat)&&isFinite(lon))addTurbine(lat,lon,name)}fitAll();log(`Imported ${S.turbines.length} WTG points`)}
function importKML(txt){S.turbines=[];const re=/<Placemark[\s\S]*?<\/Placemark>/gi;let m;while((m=re.exec(txt))){const b=m[0],name=(b.match(/<name[^>]*>([\s\S]*?)<\/name>/i)?.[1]||'').replace(/<[^>]+>/g,'');const cm=b.match(/<Point[\s\S]*?<coordinates[^>]*>([\s\S]*?)<\/coordinates>/i);if(cm){const [lon,lat]=cm[1].trim().split(/\s+/)[0].split(',').map(Number);if(isFinite(lat)&&isFinite(lon))addTurbine(lat,lon,name)}}fitAll();log(`Imported ${S.turbines.length} KML/KMZ WTG points`)}
function importGeoJSON(g){const feats=g.type==='FeatureCollection'?g.features:[g];for(const f of feats){const geom=f.geometry||f;if(geom.type==='Polygon'){const poly=geom.coordinates[0].map(c=>[c[1],c[0]]);if(!S.boundary.length)S.boundary=poly;else S.constraints.push(poly)}if(geom.type==='Point')addTurbine(geom.coordinates[1],geom.coordinates[0],f.properties?.name)}drawAll();fitAll();log('GeoJSON imported')}
function exportLayout(){let c='name,lat,lon,hh\n'+S.turbines.map(t=>`${t.name},${t.lat},${t.lon},${t.hh||P().hubH}`).join('\n');dl('layout.csv',c,'text/csv')}
function exportKML(){let k='<?xml version="1.0"?><kml><Document>'+S.turbines.map(t=>`<Placemark><name>${t.name}</name><Point><coordinates>${t.lon},${t.lat},0</coordinates></Point></Placemark>`).join('')+'</Document></kml>';dl('layout.kml',k,'application/vnd.google-earth.kml+xml')}
function dl(n,t,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function downloadTerrain(){const p=P(),radKm=+$('terrR').value,N=Math.max(8,Math.min(35,+$('terrN').value||20)),dLat=radKm/111.32,dLon=radKm/(111.32*Math.cos(rad(p.lat))||1);const lat0=p.lat-dLat,lat1=p.lat+dLat,lon0=p.lon-dLon,lon1=p.lon+dLon;const grid=[];try{for(let i=0;i<N;i++){grid[i]=[];const la=[];const lo=[];for(let j=0;j<N;j++){la.push((lat0+i*(lat1-lat0)/(N-1)).toFixed(6));lo.push((lon0+j*(lon1-lon0)/(N-1)).toFixed(6))}const r=await fetch(`https://api.open-meteo.com/v1/elevation?latitude=${la.join(',')}&longitude=${lo.join(',')}`);if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();for(let j=0;j<N;j++)grid[i][j]=d.elevation?.[j]??0;await new Promise(res=>setTimeout(res,250))}}catch(e){for(let i=0;i<N;i++){grid[i]=[];for(let j=0;j<N;j++)grid[i][j]=0}log('Terrain API failed; using flat fallback: '+e.message,'W')}const vals=grid.flat(),min=Math.min(...vals),max=Math.max(...vals),mean=vals.reduce((a,b)=>a+b,0)/vals.length;S.terrain={grid,lat0,lat1,lon0,lon1,N,min,max,mean};drawTerrain();log(`Terrain ready ${N}×${N}, ${min.toFixed(0)}-${max.toFixed(0)}m`)}
function drawTerrain(){S.layers.terrain.clearLayers();if(!S.terrain)return;const T=S.terrain,op=+$('terrainOp').value;const dLat=(T.lat1-T.lat0)/(T.N-1),dLon=(T.lon1-T.lon0)/(T.N-1);for(let i=0;i<T.N-1;i++)for(let j=0;j<T.N-1;j++){const z=T.grid[i][j],h=220-(z-T.min)/Math.max(1,T.max-T.min)*180;L.rectangle([[T.lat0+i*dLat,T.lon0+j*dLon],[T.lat0+(i+1)*dLat,T.lon0+(j+1)*dLon]],{stroke:false,fillColor:`hsl(${h},80%,50%)`,fillOpacity:op,interactive:false}).addTo(S.layers.terrain)}}
async function roughness(){S.roughness=[];try{const b=S.boundary.length?L.latLngBounds(S.boundary):map.getBounds();const q=`[out:json][timeout:25][bbox:${b.getSouth()},${b.getWest()},${b.getNorth()},${b.getEast()}];(way["landuse"];way["natural"~"wood|water|scrub|grassland|wetland|sand"];relation["landuse"]["type"="multipolygon"];);out geom;`;const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:'data='+encodeURIComponent(q)});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();const zmap={water:.0002,forest:1.5,wood:1.5,residential:.4,industrial:.5,grass:.03,farmland:.03,sand:.003,scrub:.05};S.roughness=(d.elements||[]).filter(e=>e.geometry).map(e=>{const lu=e.tags?.landuse||e.tags?.natural||'other';return{z0:zmap[lu]||.03,lu,pts:e.geometry.map(p=>[p.lat,p.lon])}});log(`Roughness polygons ${S.roughness.length}`)}catch(e){log('Roughness API failed; using project z0 fallback: '+e.message,'W')}drawRough()}
function drawRough(){S.layers.rough.clearLayers();const op=+$('roughOp').value;for(const r of S.roughness.slice(0,400))L.polygon(r.pts,{color:'#22c55e',weight:.8,fillOpacity:op,interactive:false}).addTo(S.layers.rough)}
function parseGwc(txt){const lines=txt.split(/\r?\n/).map(l=>l.trim()).filter(Boolean),idx=lines.findIndex(l=>/^\d+\s+\d+\s+\d+/.test(l));if(idx<0)throw Error('Invalid GWA lib');const [nr,nh,ns]=lines[idx].split(/\s+/).map(Number),rough=lines[idx+1].split(/\s+/).map(Number),height=lines[idx+2].split(/\s+/).map(Number);let p=idx+3;const A={},k={},freq={};for(const r of rough){freq[r]=lines[p++].split(/\s+/).map(Number);A[r]={};k[r]={};for(const h of height){A[r][h]=lines[p++].split(/\s+/).map(Number);k[r][h]=lines[p++].split(/\s+/).map(Number)}}return{rough,height,sector:Array.from({length:ns},(_,i)=>i*360/ns),A,k,freq}}
function setClimateFromGwc(txt){const g=parseGwc(txt),p=P(),r=g.rough.reduce((a,b)=>Math.abs(b-p.z0)<Math.abs(a-p.z0)?b:a,g.rough[0]);let lo=Math.max(...g.height.filter(h=>h<=p.hubH)),hi=Math.min(...g.height.filter(h=>h>=p.hubH));if(!isFinite(lo))lo=g.height[0];if(!isFinite(hi))hi=g.height.at(-1);const w=lo===hi?0:(Math.log(p.hubH)-Math.log(lo))/(Math.log(hi)-Math.log(lo));const sectors=g.sector.map((d,i)=>{const A=(1-w)*g.A[r][lo][i]+w*g.A[r][hi][i],k=(1-w)*g.k[r][lo][i]+w*g.k[r][hi][i];return{dir:d,freq:g.freq[r][i]/100,A,k}});normFreq(sectors);S.climate={source:'GWA .lib',sectors,height:p.hubH,mean:meanClimate(sectors)};log(`GWA climate ${S.climate.mean.toFixed(2)} m/s @ HH`);drawWindMap();refresh()}
async function gwa(){const p=P(),proxy=$('proxyUrl').value.trim();try{let txt='';if(proxy){const u=new URL(proxy);u.searchParams.set('lat',p.lat);u.searchParams.set('lon',p.lon);txt=await (await fetch(u)).text()}else txt=await (await fetch(`https://globalwindatlas.info/api/gwa/custom/Lib/?lat=${p.lat}&long=${p.lon}`)).text();setClimateFromGwc(txt)}catch(e){if(S.era5){setClimateFromTS(S.era5.records,'ERA5 fallback climate');log('GWA blocked; using ERA5 fallback','W')}else log('GWA blocked by browser/CORS. Add proxy, import .lib, or download ERA5 first.','W')}}
function normFreq(s){const tot=s.reduce((a,b)=>a+b.freq,0)||1;s.forEach(x=>x.freq/=tot)}function meanClimate(s){return s.reduce((a,x)=>a+x.freq*x.A*gamma(1+1/x.k),0)}
async function era5(){const p=P(),[y1,y2]=$('years').value.split('-').map(Number);const rec=[];for(let y=y1;y<=y2;y++){const u=`https://archive-api.open-meteo.com/v1/archive?latitude=${p.lat}&longitude=${p.lon}&start_date=${y}-01-01&end_date=${y}-12-31&hourly=wind_speed_100m,wind_direction_100m,temperature_2m,surface_pressure&wind_speed_unit=ms&timezone=UTC`;const d=await (await fetch(u)).json();const n=d.hourly?.time?.length||0;for(let i=0;i<n;i++)rec.push({time:d.hourly.time[i],ws:d.hourly.wind_speed_100m[i],wd:d.hourly.wind_direction_100m[i],temp:d.hourly.temperature_2m?.[i],pres:d.hourly.surface_pressure?.[i]});log(`ERA5 ${y}: ${n} records`)}S.era5={source:'ERA5',height:100,records:rec};log(`ERA5 complete ${rec.length} records`)}
function setClimateFromTS(records,source='Time-series climate'){const p=P(),bins=Array.from({length:12},()=>[]),ratio=Math.log(p.hubH/p.z0)/Math.log(100/p.z0);for(const r of records){if(r.ws==null||r.ws<.1)continue;bins[Math.floor(((r.wd||0)+15)/30)%12].push(r.ws*ratio)}const sectors=bins.map((a,i)=>{if(a.length<3)return{dir:i*30,freq:0,A:7,k:2};const m=a.reduce((x,y)=>x+y,0)/a.length,sd=Math.sqrt(a.reduce((x,y)=>x+(y-m)**2,0)/a.length),cv=Math.max(.05,sd/m),k=Math.max(1.1,Math.min(5,Math.pow(cv,-1.086))),A=m/gamma(1+1/k);return{dir:i*30,freq:a.length,A,k}});normFreq(sectors);S.climate={source,sectors,height:p.hubH,mean:meanClimate(sectors)};drawWindMap();refresh()}
function parseMastClimate(txt){const lines=txt.split(/\r?\n/).filter(Boolean),sep=lines[0].includes(';')?';':',',h=lines[0].toLowerCase().split(sep).map(x=>x.trim());const sectors=[];for(const l of lines.slice(1)){const c=l.split(sep);const get=names=>+c[h.findIndex(x=>names.includes(x))];const dir=get(['sector','dir','direction']),freq=get(['freq_pct','frequency_pct','freq','frequency']),A=get(['a','weibull_a','scale']),k=get(['k','weibull_k','shape']);if(isFinite(dir)&&isFinite(freq)&&isFinite(A)&&isFinite(k))sectors.push({dir,freq:freq>1?freq/100:freq,A,k})}normFreq(sectors);const p=P(),ratio=Math.log(p.hubH/p.z0)/Math.log(p.refH/p.z0);sectors.forEach(s=>s.A*=ratio);S.climate={source:'LT mast climate',sectors,height:p.hubH,mean:meanClimate(sectors)};log(`LT climate imported ${S.climate.mean.toFixed(2)} m/s`);refresh()}
function parseMastTS(txt){const lines=txt.split(/\r?\n/).filter(Boolean),sep=lines[0].includes(';')?';':(lines[0].includes('\t')?'\t':','),h=lines[0].toLowerCase().split(sep).map(x=>x.trim());const find=names=>h.findIndex(x=>names.some(n=>x.includes(n)));const ti=find(['timestamp','datetime','date']),wi=find(['speed','ws']),di=find(['direction','dir','wd']);const rec=[];for(const l of lines.slice(1)){const c=l.split(sep).map(x=>x.trim());const ws=+c[wi],wd=+c[di];if(isFinite(ws)&&isFinite(wd))rec.push({time:c[ti]||String(rec.length),ws,wd})}S.mastTS={source:'Mast TS',height:P().refH,records:rec};log(`Mast TS imported ${rec.length} records`)}
function importPC(txt){const lines=txt.split(/\r?\n/).filter(Boolean),sep=lines[0].includes(';')?';':',';const h=lines[0].toLowerCase().split(sep).map(x=>x.trim());const pts=[];for(const l of lines.slice(1)){const c=l.split(sep);const ws=+c[h.findIndex(x=>x.includes('ws')||x.includes('speed'))],p=+c[h.findIndex(x=>x.includes('power')||x==='kw')],cti=h.findIndex(x=>x==='ct'||x.includes('thrust')),ct=cti>=0?+c[cti]:null;if(isFinite(ws)&&isFinite(p))pts.push({ws,p,ct:isFinite(ct)?ct:null})}pts.sort((a,b)=>a.ws-b.ws);S.pc=pts;$('rated').value=Math.max(...pts.map(x=>x.p));log(`Power/CT curve imported ${pts.length} rows`)}
function pcPower(ws){if(S.pc?.length){const pc=S.pc;if(ws<pc[0].ws||ws>=pc.at(-1).ws)return 0;for(let i=0;i<pc.length-1;i++)if(ws>=pc[i].ws&&ws<pc[i+1].ws){const t=(ws-pc[i].ws)/(pc[i+1].ws-pc[i].ws||1);return pc[i].p+t*(pc[i+1].p-pc[i].p)}}const p=P();if(ws<3||ws>=25)return 0;if(ws>=10.6)return p.rated;return p.rated*Math.pow((ws-3)/(10.6-3),3)}
function pcCt(ws){if(S.pc?.length){const pc=S.pc;if(ws<pc[0].ws||ws>=pc.at(-1).ws)return 0;for(let i=0;i<pc.length-1;i++)if(ws>=pc[i].ws&&ws<pc[i+1].ws&&pc[i].ct!=null&&pc[i+1].ct!=null){const t=(ws-pc[i].ws)/(pc[i+1].ws-pc[i].ws||1);return pc[i].ct+t*(pc[i+1].ct-pc[i].ct)}}return ws<3||ws>=25?0:ws<10.6?.8:.3}
function z0At(lat,lon){for(const r of S.roughness)if(pointInPoly([lat,lon],r.pts))return r.z0;return P().z0}
function terrainAt(lat,lon){const T=S.terrain;if(!T)return 0;if(lat<T.lat0||lat>T.lat1||lon<T.lon0||lon>T.lon1)return T.mean;const y=(lat-T.lat0)/(T.lat1-T.lat0)*(T.N-1),x=(lon-T.lon0)/(T.lon1-T.lon0)*(T.N-1),i=Math.max(0,Math.min(T.N-2,Math.floor(y))),j=Math.max(0,Math.min(T.N-2,Math.floor(x))),fy=y-i,fx=x-j;return T.grid[i][j]*(1-fx)*(1-fy)+T.grid[i][j+1]*fx*(1-fy)+T.grid[i+1][j]*(1-fx)*fy+T.grid[i+1][j+1]*fx*fy}
function siteRatio(t,dir){const p=P(),z=z0At(t.lat,t.lon),rough=Math.log(p.hubH/z)/Math.log(p.hubH/p.z0);let oro=1;if(S.terrain){const d=1000,th=rad(dir),la=t.lat+Math.cos(th)*d/111320,lo=t.lon+Math.sin(th)*d/(111320*Math.cos(rad(t.lat))||1),slope=(terrainAt(t.lat,t.lon)-terrainAt(la,lo))/d;oro=Math.max(.75,Math.min(1.35,Math.exp(1.6*slope)))}return Math.max(.55,Math.min(1.65,rough*oro))}
function wakeSpeeds(free,dir){const p=P(),n=S.turbines.length,R=p.D/2,k=p.wakeK,lat0=S.turbines.reduce((a,t)=>a+t.lat,0)/n,lon0=S.turbines.reduce((a,t)=>a+t.lon,0)/n,mx=111320*Math.cos(rad(lat0)),my=111320,pts=S.turbines.map(t=>({x:(t.lon-lon0)*mx,y:(t.lat-lat0)*my})),th=rad(dir),ux=-Math.sin(th),uy=-Math.cos(th),vx=Math.cos(th),vy=-Math.sin(th),proj=pts.map(q=>q.x*ux+q.y*uy),cross=pts.map(q=>q.x*vx+q.y*vy),ord=[...Array(n).keys()].sort((a,b)=>proj[a]-proj[b]),sp=[...free];for(const j of ord){let ds=0;for(const i of ord){if(proj[i]>=proj[j]-1)continue;const dx=proj[j]-proj[i],dy=Math.abs(cross[j]-cross[i]),Rw=R+k*dx;if(dy>Rw+R)continue;const def=(1-Math.sqrt(Math.max(0,1-pcCt(sp[i]))))*Math.pow(R/Rw,2);ds+=def*def}if(ds>0)sp[j]=free[j]*(1-Math.sqrt(ds))}return sp}
function runAEP(){if(!S.climate)return alert('Download/import GWA, ERA5 fallback, or LT mast climate first');const p=P(),gross=Array(S.turbines.length).fill(0),wake=Array(S.turbines.length).fill(0),wsSum=Array(S.turbines.length).fill(0),cnt=Array(S.turbines.length).fill(0);for(const sec of S.climate.sectors){for(let v=.5;v<=32;v+=.5){const prob=sec.freq*(sec.k/sec.A)*Math.pow(v/sec.A,sec.k-1)*Math.exp(-Math.pow(v/sec.A,sec.k))*.5;if(prob<1e-9)continue;const free=S.turbines.map(t=>v*siteRatio(t,sec.dir));const wsp=wakeSpeeds(free,sec.dir);for(let i=0;i<S.turbines.length;i++){gross[i]+=pcPower(free[i])*prob*8760;wake[i]+=pcPower(wsp[i])*prob*8760;wsSum[i]+=free[i]*prob;cnt[i]+=prob}}}const loss=1-p.loss;const per=S.turbines.map((t,i)=>({name:t.name,lat:t.lat,lon:t.lon,ws:wsSum[i]/(cnt[i]||1),gross:gross[i]/1e6,wake:(gross[i]-wake[i])/Math.max(1,gross[i])*100,net:wake[i]*loss/1e6,cf:wake[i]*loss/(p.rated*8760)*100}));const net=per.reduce((a,b)=>a+b.net,0),gr=per.reduce((a,b)=>a+b.gross,0);S.results={per,net,gross:gr,wake:(gr-net/loss)/gr*100,cf:net*1000/(S.turbines.length*p.rated/1000*8760)*100};log(`AEP net ${net.toFixed(2)} GWh`);refresh()}
function runTS(){const src=S.mastTS||S.era5;if(!src)return alert('Import mast TS or download ERA5 first');const p=P(),recs=src.records,fromH=src.height||100,ratio=Math.log(p.hubH/p.z0)/Math.log(fromH/p.z0),loss=1-p.loss;const per=S.turbines.map(t=>({name:t.name,net:0,gross:0,ws:0,n:0}));let farm=0,gfarm=0;for(let r=0;r<recs.length;r++){const rec=recs[r];if(rec.ws==null)continue;const ws=rec.ws*ratio,free=S.turbines.map(t=>ws*siteRatio(t,rec.wd||0)),wsp=wakeSpeeds(free,rec.wd||0);for(let i=0;i<S.turbines.length;i++){const g=pcPower(free[i]),n=pcPower(wsp[i])*loss;per[i].gross+=g;per[i].net+=n;per[i].ws+=free[i];per[i].n++;gfarm+=g;farm+=n}}per.forEach(t=>{t.gross/=1e6;t.net/=1e6;t.ws/=Math.max(1,t.n);t.cf=t.net*1e6/(p.rated*8760)*100});S.ts={source:src.source,per,net:farm/1e6,gross:gfarm/1e6,cf:farm/(S.turbines.length*p.rated*8760)*100};log(`TS net ${S.ts.net.toFixed(2)} GWh`);refresh()}
function optimise(){if(!S.boundary.length)return alert('Draw/import boundary first');const p=P(),target=+$('targetMW').value,minD=+$('minD').value,need=Math.ceil(target/(p.rated/1000)),b=L.latLngBounds(S.boundary),spacing=minD*p.D,mLat=111320,mLon=111320*Math.cos(rad(b.getCenter().lat)),dLat=spacing/mLat,dLon=spacing/mLon;S.turbines=[];let row=0;for(let lat=b.getSouth();lat<=b.getNorth()&&S.turbines.length<need;lat+=dLat,row++){for(let lon=b.getWest()+(($('optPattern').value==='stagger'&&row%2)?dLon/2:0);lon<=b.getEast()&&S.turbines.length<need;lon+=dLon){const pt=[lat,lon];if(!pointInPoly(pt,S.boundary))continue;if(S.constraints.some(c=>pointInPoly(pt,c)))continue;addTurbine(lat,lon)}}drawAll();fitAll();log(`Optimised ${S.turbines.length}/${need} WTGs inside boundary`)}
function drawWindMap(){S.layers.wind.clearLayers();if(!S.climate||!S.turbines.length)return;const op=+$('windOp').value;for(const t of S.turbines){const sr=S.climate.mean*siteRatio(t,270);L.circle([t.lat,t.lon],{radius:400,color:'#7dd3fc',fillColor:'#7dd3fc',fillOpacity:op,weight:1}).bindPopup(`${t.name}<br>Free WS ~${sr.toFixed(2)} m/s`).addTo(S.layers.wind)}}
function refresh(){const p=P();$('tab-summary').innerHTML=`<div class=cards><div class=card><div class=big>${S.turbines.length}</div>WTGs</div><div class=card><div class=big>${(S.turbines.length*p.rated/1000).toFixed(1)}</div>MW</div><div class=card><div class=big>${S.climate?S.climate.mean.toFixed(2):'—'}</div>Ref HH WS</div><div class=card><div class=big>${S.results?S.results.net.toFixed(1):'—'}</div>Net GWh/y</div></div>`;$('tab-chain').innerHTML=`<table><tr><th>Stage</th><th>Value</th></tr><tr><td>Climate source</td><td>${S.climate?.source||'—'}</td></tr><tr><td>Reference height</td><td>${p.refH} m</td></tr><tr><td>Hub height</td><td>${p.hubH} m</td></tr><tr><td>Air density ref</td><td>${p.rhoRef} kg/m³</td></tr></table>`;$('tab-wtg').innerHTML=S.results?'<table><tr><th>WTG</th><th>WS</th><th>Gross</th><th>Wake%</th><th>Net</th><th>CF%</th></tr>'+S.results.per.map(x=>`<tr><td>${x.name}</td><td>${x.ws.toFixed(2)}</td><td>${x.gross.toFixed(2)}</td><td>${x.wake.toFixed(1)}</td><td>${x.net.toFixed(2)}</td><td>${x.cf.toFixed(1)}</td></tr>`).join('')+'</table>':'Run AEP';$('tab-ts').innerHTML=S.ts?'<table><tr><th>WTG</th><th>WS</th><th>Gross GWh</th><th>Net GWh</th><th>CF%</th></tr>'+S.ts.per.map(x=>`<tr><td>${x.name}</td><td>${x.ws.toFixed(2)}</td><td>${x.gross.toFixed(3)}</td><td>${x.net.toFixed(3)}</td><td>${x.cf.toFixed(1)}</td></tr>`).join('')+'</table>':'Run time series';drawWindMap();}
function report(){const html=`<html><body><h1>${P().project}</h1><p>WTGs: ${S.turbines.length}</p><p>Climate: ${S.climate?.source||''}, mean ${S.climate?.mean?.toFixed(2)||''} m/s</p><p>Net AEP: ${S.results?.net?.toFixed(2)||''} GWh</p>${$('tab-wtg').innerHTML}</body></html>`;dl('WindFlow_Pro_Report.html',html,'text/html')}
function demo(){S.turbines=[];const p=P(),mx=111320*Math.cos(rad(p.lat)),my=111320;for(let r=0;r<3;r++)for(let c=0;c<4;c++)addTurbine(p.lat+(r-1)*p.D*7/my,p.lon+(c-1.5)*p.D*7/mx);fitAll();refresh()}
function bind(){for(const id of ['terrainOp','roughOp','windOp'])$(id).oninput=drawAll;$('demoBtn').onclick=demo;$('drawBoundary').onclick=()=>{S.mode='boundary';S.tempPoly=[];log('Boundary draw mode')};$('drawConstraint').onclick=()=>{S.mode='constraint';S.tempPoly=[];log('Constraint draw mode')};$('addWtgMode').onclick=()=>{S.mode='wtg';log('Add WTG mode')};$('closePoly').onclick=closePoly;$('clearDraw').onclick=clearDraw;$('importGeo').onclick=async()=>{const f=$('geoFile').files[0];if(f)await importFile(f);refresh()};$('exportLayout').onclick=exportLayout;$('exportKml').onclick=exportKML;$('terrBtn').onclick=downloadTerrain;$('roughBtn').onclick=roughness;$('gwaBtn').onclick=gwa;$('gwaImport').onclick=async()=>{const f=$('gwaFile').files[0];if(f)setClimateFromGwc(await f.text());refresh()};$('eraBtn').onclick=era5;$('mastClimateBtn').onclick=async()=>{const f=$('mastClimate').files[0];if(f)parseMastClimate(await f.text())};$('mastTsBtn').onclick=async()=>{const f=$('mastTs').files[0];if(f)parseMastTS(await f.text())};$('pcBtn').onclick=async()=>{const f=$('pcFile').files[0];if(f)importPC(await f.text())};$('optBtn').onclick=optimise;$('runBtn').onclick=runAEP;$('tsBtn').onclick=runTS;$('reportBtn').onclick=report;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tabbody').forEach(x=>x.classList.remove('on'));b.classList.add('on');$(`tab-${b.dataset.tab}`).classList.add('on')})}
window.addEventListener('load',()=>{initMap();bind();demo();log('WindFlow Studio Pro v2 ready')});
